# Generated by Django 3.2.8 on 2021-11-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='updateDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
